### ISSUE TITLE
New UI: Test names unhelpfully truncated

### ISSUE THREAD

**Issue by nstielau** [openshift/sippy#266]
The new UI looks great!

Problem: The test names are cut a bit too short, especially since many of them have prefixes.  

Possible solution: 
* Remove the two-column display for more detail (at the cost of more scrolling)
* Squish in the percentages (we probably don't need anything past the decimal point) to give more space to test names.

![image](https://user-images.githubusercontent.com/30011/130489425-f8d94713-f3dc-4f1f-9f05-816e225c5a64.png)

**Comment by bparees** [comment]
the old sippy ui just uses multiline rows for this:

![image](https://user-images.githubusercontent.com/4974046/130492494-58770f94-103b-4ba2-848c-332e2c2a41a2.png)


so that might be an option too

**Comment by stbenjam** [comment]
Data grid tables don't support dynamic row heights ( https://github.com/mui-org/material-ui-x/issues/417), which is why I used the ellipsis and tooltip, but I realize I don't need dynamic row heights - they can all be the same size, just taller.


I also removed the decimal points. What do you think of these? Any changes?

![image](https://user-images.githubusercontent.com/429763/130531087-881dca22-e62d-44af-b43e-a329c4a2593c.png)


![image](https://user-images.githubusercontent.com/429763/130531175-0637e9ea-7853-44c1-9b8f-b42eb99ef94c.png)

**Comment by stbenjam** [comment]
And test-by-variant page:

![image](https://user-images.githubusercontent.com/429763/130532235-a2c8587c-e22f-4391-94d6-b281ee61fdfc.png)
